Store/Store/Store/Models/Kniga.cs
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Store.Models
{
    public class Kniga
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Naslov { get; set; }


        public int? Godina { get; set; }
        public int? BrStrani { get; set; }


        [StringLength(int.MaxValue)]
        public string? Opis{ get; set; }


        [StringLength(50)]
        public string? Zanr { get; set; }

        public int? Tirazh { get; set; }


        [StringLength(100)]
        public string? Izdavac { get; set; }


        [StringLength(int.MaxValue)]
        [Display(Name = "Slika")]

        public string? SlikaUrl { get; set; }
        [NotMapped]
        public IFormFile? SlikaFile { get; set; }

        public ICollection<AvtorKniga>? Avtori { get; set; }
    }
}

Store/Store/Store/Controllers/AvtorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Store.Data;
using Store.Models;
using Store.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace Store.Controllers
{
    public class AvtorsController : Controller
    {
        private readonly StoreContext _context;

        public AvtorsController(StoreContext context)
        {
            _context = context;
        }

        // GET: Avtors
        public async Task<IActionResult> Index(string searchStringI, string searchStringP, string searchStringN)
        {

            IQueryable<Avtor> avtori = _context.Avtor.AsQueryable();
    
            if (!string.IsNullOrEmpty(searchStringI))
            {
               avtori=avtori.Where(s => s.Ime.Contains(searchStringI));
            }
            if (!string.IsNullOrEmpty(searchStringP))
            {
                avtori = avtori.Where(s => s.Prezime.Contains(searchStringP));
            }
            if (!string.IsNullOrEmpty(searchStringN))
            {
                avtori = avtori.Where(s => s.Nacionalnost.Contains(searchStringN));
            }
            avtori=avtori.Include(m => m.Knigi).ThenInclude(m => m.Kniga);
            var AvtorVM = new AvtorViewModel
            {
                Avtori = await avtori.ToListAsync(),
            };
            return View(AvtorVM);
        }

        // GET: Avtors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var avtor = await _context.Avtor
                .Include(a => a.Knigi)
                .ThenInclude(m => m.Kniga)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (avtor == null)
            {
                return NotFound();
            }

            return View(avtor);
        }

        // GET: Avtors/Create
        [HttpGet]
        public IActionResult Create()
        {
            var knigaList = _context.Kniga.Select(g => new SelectListItem { Value = g.Id.ToString(), Text = g.Naslov }).ToList();
            return View(new KnigaAvtorEditViewModel { KnigaList = knigaList });
        }

        // POST: Knigas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(KnigaAvtorEditViewModel bookVM)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bookVM.avtor);
                await _context.SaveChangesAsync();
                if (bookVM.SelectedKnigas != null && bookVM.SelectedKnigas.Any())
                {
                    foreach (var knigaId in bookVM.SelectedKnigas)
                    {
                        _context.AvtorKniga.Add(new AvtorKniga { AvtorId = bookVM.avtor.Id, KnigaId = knigaId });
                    }
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["KnigaId"] = new SelectList(_context.Set<Kniga>(), "Id", "Naslov");
            return View(bookVM);
        }

        // GET: Knigas/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var avtor = await _context.Avtor
                .Where(m => m.Id == id)
                .Include(m => m.Knigi)
                .ThenInclude(m => m.Kniga)
                .FirstOrDefaultAsync();

            if (avtor == null)
            {
                return NotFound();
            }

            var knigi = _context.Kniga
                .AsEnumerable()  // Switch to client-side evaluation
                .OrderBy(s => s.Naslov);

            KnigaAvtorEditViewModel viewmodel = new KnigaAvtorEditViewModel
            {
                avtor=avtor,
                KnigaList = new MultiSelectList(knigi, "Id", "Naslov"),
                SelectedKnigas = avtor.Knigi.Select(sa => sa.KnigaId)
            };

            return View(viewmodel);
        }

        // POST: Knigas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, KnigaAvtorEditViewModel viewmodel)
        {
            if (id != viewmodel.avtor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viewmodel.avtor);
                    await _context.SaveChangesAsync();

                    var newKnigaList = viewmodel.SelectedKnigas;
                    var prevKnigaList = _context.AvtorKniga.Where(s => s.AvtorId == id).Select(s => s.KnigaId);

                    var toBeRemoved = _context.AvtorKniga.Where(s => s.AvtorId == id);
                    if (newKnigaList != null)
                    {
                        toBeRemoved = toBeRemoved.Where(s => !newKnigaList.Contains(s.KnigaId));
                        foreach (var knigaId in newKnigaList)
                        {
                            if (!prevKnigaList.Any(s => s == knigaId))
                            {
                                _context.AvtorKniga.Add(new AvtorKniga { KnigaId = knigaId, AvtorId = id });
                            }
                        }
                    }

                    _context.AvtorKniga.RemoveRange(toBeRemoved);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AvtorExists(viewmodel.avtor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(viewmodel);
        }

        // GET: Avtors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var avtor = await _context.Avtor
                .Include(a =>a.Knigi)
                .ThenInclude(a=>a.Kniga)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (avtor == null)
            {
                return NotFound();
            }

            return View(avtor);
        }

        // POST: Avtors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var avtor = await _context.Avtor.FindAsync(id);
            if (avtor != null)
            {
                _context.Avtor.Remove(avtor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AvtorExists(int id)
        {
            return _context.Avtor.Any(e => e.Id == id);
        }
    }
}

Store/Store/Store/Controllers/KnigasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Store.Data;
using Store.Models;
using Store.ViewModels;

namespace Store.Controllers
{
    public class KnigasController : Controller
    {
        private readonly StoreContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public KnigasController(StoreContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment =webHostEnvironment;
        }

        // GET: Knigas
        public async Task<IActionResult> Index(string knigaZanr, string searchStringN, string searchStringG, string searchStringI)
        {
            IQueryable<Kniga> knigi = _context.Kniga.AsQueryable();
            IQueryable<string> genreQuery = _context.Kniga.OrderBy(m => m.Zanr).Select(m => m.Zanr).Distinct();

            if (!string.IsNullOrEmpty(searchStringN))
            {
                knigi = knigi.Where(s => s.Naslov.Contains(searchStringN));
            }
            if (!string.IsNullOrEmpty(searchStringG))
            {
                if (int.TryParse(searchStringG, out int year))
                {
                    knigi = knigi.Where(s => s.Godina == year);
                }
            }
            if (!string.IsNullOrEmpty(searchStringI))
            {
                knigi = knigi.Where(s => s.Izdavac.Contains(searchStringI));
            }
            if (!string.IsNullOrEmpty(knigaZanr))
            {
                knigi = knigi.Where(x => x.Zanr == knigaZanr);
            }

            knigi = knigi.Include(m => m.Avtori).ThenInclude(m => m.Avtor);

            var bookGenreVM = new KnigaZanrViewModel
            {
                Zanrovi = new SelectList(await genreQuery.ToListAsync()),
                Knigi = await knigi.ToListAsync()
            };

            return View(bookGenreVM);
        }

        // GET: Knigas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kniga = await _context.Kniga
                .Include(m => m.Avtori)
                .ThenInclude(m => m.Avtor)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (kniga == null)
            {
                return NotFound();
            }

            return View(kniga);
        }

        // GET: Knigas/Create
        [HttpGet]
        public IActionResult Create()
        {
            var avtorList = _context.Avtor.Select(g => new SelectListItem { Value = g.Id.ToString(), Text = g.FullName }).ToList();
            return View(new AvtorKnigaEditViewModel { AvtorList = avtorList });
        }

        // POST: Knigas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AvtorKnigaEditViewModel bookVM)
        {
            if (ModelState.IsValid)
            {
                if (bookVM.kniga.SlikaFile != null && bookVM.kniga.SlikaFile.Length > 0)
                {
                    var uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                    var uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(bookVM.kniga.SlikaFile.FileName);
                    var filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await bookVM.kniga.SlikaFile.CopyToAsync(fileStream);
                    }
                    bookVM.kniga.SlikaUrl = uniqueFileName;
                }
                _context.Add(bookVM.kniga);
                await _context.SaveChangesAsync();
                if (bookVM.SelectedAvtors != null && bookVM.SelectedAvtors.Any())
                {
                    foreach (var avtorId in bookVM.SelectedAvtors)
                    {
                        _context.AvtorKniga.Add(new AvtorKniga { KnigaId = bookVM.kniga.Id, AvtorId = avtorId });
                    }
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["AvtorId"] = new SelectList(_context.Set<Avtor>(), "Id", "FullName");
            return View(bookVM);
        }

        // GET: Knigas/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kniga = await _context.Kniga
                .Where(m => m.Id == id)
                .Include(m => m.Avtori)
                .ThenInclude(m => m.Avtor)
                .FirstOrDefaultAsync();

            if (kniga == null)
            {
                return NotFound();
            }

            var avtors = _context.Avtor
                .AsEnumerable()  // Switch to client-side evaluation
                .OrderBy(s => s.FullName);

            AvtorKnigaEditViewModel viewmodel = new AvtorKnigaEditViewModel
            {
                kniga = kniga,
                AvtorList = new MultiSelectList(avtors, "Id", "FullName"),
                SelectedAvtors = kniga.Avtori.Select(sa => sa.AvtorId)
            };

            return View(viewmodel);
        }

        // POST: Knigas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, AvtorKnigaEditViewModel viewmodel)
        {
            if (id != viewmodel.kniga.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (viewmodel.kniga.SlikaFile != null && viewmodel.kniga.SlikaFile.Length > 0)
                    {
                        var uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                        var uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(viewmodel.kniga.SlikaFile.FileName);
                        var filePath = Path.Combine(uploadsFolder, uniqueFileName);
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await viewmodel.kniga.SlikaFile.CopyToAsync(fileStream);
                        }
                        viewmodel.kniga.SlikaUrl = uniqueFileName;
                    }
                    _context.Update(viewmodel.kniga);
                    await _context.SaveChangesAsync();

                    var newAvtorList = viewmodel.SelectedAvtors;
                    var prevAvtorList = _context.AvtorKniga.Where(s => s.KnigaId == id).Select(s => s.AvtorId);

                    var toBeRemoved = _context.AvtorKniga.Where(s => s.KnigaId == id);
                    if (newAvtorList != null)
                    {
                        toBeRemoved = toBeRemoved.Where(s => !newAvtorList.Contains(s.AvtorId));
                        foreach (var avtorId in newAvtorList)
                        {
                            if (!prevAvtorList.Any(s => s == avtorId))
                            {
                                _context.AvtorKniga.Add(new AvtorKniga { AvtorId = avtorId, KnigaId = id });
                            }
                        }
                    }

                    _context.AvtorKniga.RemoveRange(toBeRemoved);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KnigaExists(viewmodel.kniga.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(viewmodel);
        }

        // GET: Knigas/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kniga = await _context.Kniga.Include(b=>b.Avtori).ThenInclude(b=>b.Avtor).FirstOrDefaultAsync(m => m.Id == id);
            if (kniga == null)
            {
                return NotFound();
            }

            return View(kniga);
        }

        // POST: Knigas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kniga = await _context.Kniga.FindAsync(id);
            if (kniga != null)
            {
                _context.Kniga.Remove(kniga);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool KnigaExists(int id)
        {
            return _context.Kniga.Any(e => e.Id == id);
        }
    }
}

Store/Store/Store/Views/Knigas/Create.cshtml
@model Store.ViewModels.AvtorKnigaEditViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Kniga</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="kniga.Naslov" class="control-label"></label>
                <input asp-for="kniga.Naslov" class="form-control" />
                <span asp-validation-for="kniga.Naslov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="kniga.Godina" class="control-label"></label>
                <input asp-for="kniga.Godina" class="form-control" />
                <span asp-validation-for="kniga.Godina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="kniga.BrStrani" class="control-label"></label>
                <input asp-for="kniga.BrStrani" class="form-control" />
                <span asp-validation-for="kniga.BrStrani" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="kniga.Opis" class="control-label"></label>
                <input asp-for="kniga.Opis" class="form-control" />
                <span asp-validation-for="kniga.Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="kniga.Zanr" class="control-label"></label>
                <input asp-for="kniga.Zanr" class="form-control" />
                <span asp-validation-for="kniga.Zanr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="kniga.Tirazh" class="control-label"></label>
                <input asp-for="kniga.Tirazh" class="form-control" />
                <span asp-validation-for="kniga.Tirazh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="kniga.Izdavac" class="control-label"></label>
                <input asp-for="kniga.Izdavac" class="form-control" />
                <span asp-validation-for="kniga.Izdavac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="kniga.SlikaFile" class="control-label"></label>
                <input asp-for="kniga.SlikaFile" type="file" class="form-control" />
                <span asp-validation-for="kniga.SlikaFile" class="text-danger"></span>
            </div>
            <!--
            <div class="form-group">
                <label asp-for="kniga.SlikaUrl" class="control-label"></label>
                <input asp-for="kniga.SlikaUrl" class="form-control" />
                <span asp-validation-for="kniga.SlikaUrl" class="text-danger"></span>
            </div>-->
            <div class="form-group">
                <label asp-for="SelectedAvtors" class="control-label">Avtori</label>
                <select asp-for="SelectedAvtors" class="form-control" asp-items="Model.AvtorList" multiple></select>
                </select>
                <span asp-validation-for="SelectedAvtors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Store/Store/Store/Views/Knigas/Delete.cshtml
@model Store.Models.Kniga

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kniga</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Naslov)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Naslov)
        </dd>
        <dt class="col-sm-3">Slika:</dt>
        <dd class="col-sm-9">
            <img src="@Url.Content("~/images/" + Model.SlikaUrl)" alt="@Model.Naslov" style="max-width: 50%; height: auto;">
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Godina)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Godina)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BrStrani)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BrStrani)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Zanr)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Zanr)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tirazh)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tirazh)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Izdavac)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Izdavac)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Avtori)
        </dt>
        <dd class="col-sm-10">
            @foreach (var avtor in Model.Avtori)
            {
            <a asp-controller="Avtors" asp-action="Details" asp-route-id="@avtor.AvtorId">
                @avtor.Avtor.FullName
            </a>  <br />
            }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Store/Store/Store/Views/Knigas/Details.cshtml
@model Store.Models.Kniga

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Kniga</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Naslov)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Naslov)
        </dd>
        <dt class="col-sm-3">Slika:</dt>
        <dd class="col-sm-9">
            <img src="@Url.Content("~/images/" + Model.SlikaUrl)" alt="@Model.Naslov" style="max-width: 50%; height: auto;">
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Godina)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Godina)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BrStrani)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BrStrani)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Zanr)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Zanr)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tirazh)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tirazh)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Izdavac)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Izdavac)
        </dd>
        <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Avtori)</dt>
        <dd class="col-sm-9">
            @if (Model.Avtori != null && Model.Avtori.Any())
                {
                    foreach (var bookAvtor in Model.Avtori)
                    {
                        if (bookAvtor != null && bookAvtor.Avtor != null)
                        {
            <a asp-controller="Avtors" asp-action="Details" asp-route-id="@bookAvtor.AvtorId">@bookAvtor.Avtor.FullName</a>
            <br />
                        }
                    }
                }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Store/Store/Store/Views/Knigas/Index.cshtml
@model Store.ViewModels.KnigaZanrViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Knigas" asp-action="Index" method="get">
    <p>
        <select asp-for="KnigaZanr" asp-items="Model.Zanrovi">
            <option value="">All</option>
        </select>
        Naslov: <input type="text" asp-for="SearchStringN" />
        <input type="submit" value="Filter" />
        Godina: <input type="text" asp-for="SearchStringG" />
        <input type="submit" value="Filter" />
        Izdavacka kukja: <input type="text" asp-for="SearchStringI" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table cl
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Knigi[0].Naslov)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Knigi[0].Godina)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Knigi[0].BrStrani)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Knigi[0].Opis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Knigi[0].Zanr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Knigi[0].Tirazh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Knigi[0].Izdavac)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Knigi[0].SlikaUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Knigi[0].Avtori)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Knigi) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naslov)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Godina)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrStrani)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zanr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tirazh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Izdavac)
            </td>
    <td>
                <img src="@Url.Content("~/images/" + item.SlikaUrl)" class="card-img-top" alt="@item.Naslov" style="height: 300px; object-fit: cover;">
            </td>
                <td>
                    @foreach (var avtor in item.Avtori)
                    {
                        <a asp-controller="Avtors" asp-action="Details" asp-route-id="@avtor.AvtorId"> @avtor.Avtor.FullName </a> <br />
                    }
                </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>